### ISSUE TITLE
Client Server with Disk (Pipelining simulator): prevent execution  when input is invalid

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/eduwrench#39]
Somehow,  the "Run  Simulation" button still runs  the simulation when input is invalid. It seems  that's not the  case for other simulators, but Henri couldn't figure out the difference... e.g., the basic Client-Server simulator

**Comment by rafaelfsilva** [comment]
@henricasanova, I did a small fix to the javascript, but I am not sure the issue is solved. I am not experience this same problem. Which set of parameters or which procedure did you follow, so I can try to reproduce here?

**Comment by henricasanova** [comment]
It didn't fix it.  Just put small value for the buffer size (less than 50000). And you'll see.

**Comment by rafaelfsilva** [comment]
got it. I think it is fixed now, it was a matter of putting the right range of values in the form definition. We might need to check other forms too. I did some in the past, but not all of them.

**Comment by henricasanova** [comment]
I started going through all simulators, and I am encountering a problem on the first one :) (IO Operations). Entering invalid input, e.g., a number of tasks = to 0, prints the "Invalid message", the HTML form has the right value, and yet the simulator is called (it fails due to invalid argument), but still it takes one second or two.  By contrast, the client-server-pipelining simulator that you fixed above doesn't have that bad behavior, and I don't really see the difference. Some of the HTML tags are different in the two files (client_server_disk.html vs. io_operations.html), but could that be it? Sorry to be such a Web development n00b ;)

**Comment by rafaelfsilva** [comment]
I have fixed the IO operations form. It was missing a `type="number"` in the HTML form declaration.

**Comment by rafaelfsilva** [comment]
It missed the javascript to ensure the validation on `keyup`. Let me know if it looks right now.

**Comment by henricasanova** [comment]
Looks great! Closing this issue.
